// @lifecycle canonical - Manages MCP tool descriptions and discovery metadata.
/**
 * Tool Description Loader
 *
 * Manages externalized tool descriptions with framework-aware overlays.
 * Base descriptions loaded from generated contracts (tool-descriptions.contracts.json),
 * imported statically so esbuild inlines them into dist/index.js — the published package
 * ships no src/, so a disk read at runtime would find nothing in an install.
 * Overlay composition delegated to tool-description-overlays.ts: a framework's guidance is
 * appended after the contract text, never substituted for it.
 *
 * No file persistence — the in-memory descriptions Map is the runtime source of truth.
 */

import { EventEmitter } from 'events';

import {
  cloneToolDescription,
  composeParameterDescription,
  composeToolDescription,
  normalizeFrameworkKey,
  parameterText,
  preloadFrameworkDescriptions,
  preloadStyleDescriptions,
  buildActiveConfig,
  type FrameworkToolOverlay,
} from './tool-description-overlays.js';
// JSON import — esbuild inlines, tsc resolves via resolveJsonModule (matches
// operator-patterns.ts / command-parser.ts). Generated by `npm run generate:contracts`
// from tooling/contracts/*.json; never edit this file directly.
import toolDescriptionsContract from '../contracts/schemas/_generated/tool-descriptions.contracts.json' with { type: 'json' };

import type {
  FrameworkToolDescription,
  FrameworkToolDescriptions,
} from '#engine/frameworks/types/index.js';
import type { StyleToolDescriptionYaml } from '#modules/formatting/core/style-schema.js';
import type {
  ConfigManager,
  Logger,
  ToolDescription,
  ToolDescriptionsConfig,
  ResolvedFrameworkConfig,
} from '#shared/types/index.js';

import { FrameworkStateStore } from '#engine/frameworks/framework-state-store.js';

/**
 * The contract's own descriptions, one clone per call.
 *
 * This is also the fallback when composing overlays fails. It used to be a hand-written copy of
 * the three descriptions, and the copy had drifted: its `system_control` line named 7 of the 12
 * actions. The generated contract is statically imported and always present, so the fallback reads
 * it instead of restating it.
 */
function createContractDescriptionMap(): Map<string, ToolDescription> {
  return new Map(
    Object.entries(toolDescriptionsContract.tools).map(([name, description]) => [
      name,
      cloneToolDescription(description),
    ])
  );
}

/**
 * Manages tool descriptions loaded from generated contracts with framework overlays.
 *
 * Load flow:
 *   contracts JSON → in-memory Map → framework overlays applied → getDescription() serves result
 */
export class ToolDescriptionLoader extends EventEmitter {
  private logger: Logger;
  /** Contract descriptions with the state store's active framework composed onto them. */
  private descriptions: Map<string, ToolDescription>;
  /** Contract descriptions exactly as generated — the base every composition starts from. */
  private readonly contractDescriptions: Map<string, ToolDescription>;
  private frameworkDescriptions: Map<string, FrameworkToolOverlay>;
  private styleDescriptions: Map<string, Record<string, StyleToolDescriptionYaml>>;
  private isInitialized: boolean = false;
  private configManager: ConfigManager;
  private frameworksConfig: ResolvedFrameworkConfig;
  private frameworksConfigListener: (
    newConfig: ResolvedFrameworkConfig,
    previousConfig: ResolvedFrameworkConfig
  ) => void;
  private frameworkStateStore?: FrameworkStateStore;
  private lastLoadSource: 'contracts' | 'defaults' = 'defaults';
  private frameworkSwitchedListener?: (
    previousFramework: string,
    newFramework: string,
    reason: string
  ) => void;
  private frameworkToggledListener?: (enabled: boolean, reason: string) => void;

  constructor(logger: Logger, configManager: ConfigManager) {
    super();
    this.logger = logger;
    this.configManager = configManager;
    this.descriptions = new Map();
    this.contractDescriptions = createContractDescriptionMap();
    this.frameworkDescriptions = new Map();
    this.styleDescriptions = new Map();
    this.frameworksConfig = this.configManager.getFrameworksConfig();

    this.frameworksConfigListener = (newConfig: ResolvedFrameworkConfig) => {
      this.frameworksConfig = { ...newConfig };
      this.logger.info(
        `Tool description manager feature toggle updated (dynamicDescriptions: ${this.frameworksConfig.dynamicToolDescriptions})`
      );
      if (this.isInitialized) {
        void this.synchronize(
          'Framework feature config changed (dynamic tool descriptions toggle)'
        );
      }
    };

    this.configManager.on('frameworksConfigChanged', this.frameworksConfigListener);
  }

  /**
   * Base config is the statically-imported generated contract — always present at build time,
   * so there is no "not found" branch to fall back from. `contractDescriptions` is the
   * `synchronize()` catch-all for a genuinely unexpected failure (e.g. a malformed framework YAML
   * thrown from `buildActiveConfig`): the contract text uncomposed.
   */
  private loadBaseConfig(): {
    config: ToolDescriptionsConfig;
    source: 'contracts' | 'defaults';
  } {
    return { config: toolDescriptionsContract, source: 'contracts' };
  }

  private setDescriptionsFromConfig(config: ToolDescriptionsConfig): void {
    this.descriptions.clear();
    for (const [name, description] of Object.entries(config.tools)) {
      this.descriptions.set(name, cloneToolDescription(description));
    }
  }

  private getActiveFrameworkContext(): {
    activeFramework?: string;
    activeFrameworkType?: string;
    frameworkSystemEnabled?: boolean;
  } {
    if (!this.frameworkStateStore) {
      return {};
    }

    try {
      const state = this.frameworkStateStore.getCurrentState();
      const activeFramework = this.frameworkStateStore.getActiveFramework();

      return {
        activeFramework: activeFramework?.id,
        activeFrameworkType: activeFramework?.type ?? activeFramework?.id,
        frameworkSystemEnabled: state?.frameworkSystemEnabled,
      };
    } catch (error) {
      this.logger.warn(
        `[ToolDescriptionLoader] Unable to read framework state for tool descriptions: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      return {};
    }
  }

  /**
   * The overlay a caller's framework contributes to one tool, or undefined when there is none —
   * because dynamic descriptions are off, the caller opted out, the framework system is disabled,
   * or the framework says nothing about this tool.
   */
  private resolveOverlay(
    toolName: string,
    frameworkEnabled: boolean | undefined,
    activeFrameworkType: string | undefined,
    applyFrameworkOverride: boolean
  ): { label: string; tool: FrameworkToolDescription } | undefined {
    if (!applyFrameworkOverride || frameworkEnabled === false) return undefined;
    const frameworkKey = normalizeFrameworkKey(activeFrameworkType);
    if (!frameworkKey) return undefined;
    const framework = this.frameworkDescriptions.get(frameworkKey);
    const tool = framework?.tools[toolName as keyof FrameworkToolDescriptions];
    return framework && tool ? { label: framework.label, tool } : undefined;
  }

  private async synchronize(reason: string, options?: { emitChange?: boolean }): Promise<void> {
    try {
      const base = this.loadBaseConfig();
      this.lastLoadSource = base.source;
      this.frameworkDescriptions = preloadFrameworkDescriptions(this.logger);
      this.styleDescriptions = preloadStyleDescriptions(this.logger);
      const activeContext = this.getActiveFrameworkContext();
      const dynamicEnabled =
        this.frameworksConfig.dynamicToolDescriptions &&
        (activeContext.frameworkSystemEnabled ?? true);
      const activeConfig = buildActiveConfig(
        base.config,
        activeContext,
        this.frameworkDescriptions,
        dynamicEnabled
      );
      activeConfig.generatedFrom = base.source;

      this.setDescriptionsFromConfig(activeConfig);
      this.isInitialized = true;

      this.logger.info(
        `Synchronized tool descriptions (${reason}); source=${base.source}, framework=${activeContext.activeFramework || 'n/a'}, framework=${activeContext.activeFrameworkType || 'n/a'}`
      );

      if (options?.emitChange ?? true) {
        this.emit('descriptions-changed', this.getStats());
      }
    } catch (error) {
      this.logger.error(
        `[ToolDescriptionLoader] Failed to synchronize tool descriptions: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
      this.descriptions = createContractDescriptionMap();
      this.lastLoadSource = 'defaults';
      this.isInitialized = true;
      if (options?.emitChange ?? true) {
        this.emit('descriptions-error', error);
      }
    }
  }

  setFrameworkStateStore(frameworkStateStore: FrameworkStateStore): void {
    if (this.frameworkStateStore === frameworkStateStore) {
      return;
    }

    if (this.frameworkStateStore && this.frameworkSwitchedListener) {
      this.frameworkStateStore.off('framework-switched', this.frameworkSwitchedListener);
    }
    if (this.frameworkStateStore && this.frameworkToggledListener) {
      this.frameworkStateStore.off('framework-system-toggled', this.frameworkToggledListener);
    }

    this.frameworkStateStore = frameworkStateStore;

    this.frameworkSwitchedListener = async (_prev, _next, reason) => {
      await this.synchronize(`framework switched: ${reason}`);
    };
    this.frameworkToggledListener = async (enabled, reason) => {
      await this.synchronize(`framework system ${enabled ? 'enabled' : 'disabled'}: ${reason}`);
    };

    this.frameworkStateStore.on('framework-switched', this.frameworkSwitchedListener);
    this.frameworkStateStore.on('framework-system-toggled', this.frameworkToggledListener);
  }

  async initialize(): Promise<void> {
    await this.synchronize('initial load', { emitChange: false });
  }

  /**
   * The description served for one tool.
   *
   * With `activeFrameworkType` given, the result is the contract text composed with THAT
   * framework's guidance (none when `frameworkEnabled` is false). Without it, the result is the
   * active config: the contract composed with the state store's framework.
   */
  getDescription(
    toolName: string,
    frameworkEnabled?: boolean,
    activeFrameworkType?: string,
    options?: { applyFrameworkOverride?: boolean }
  ): string {
    const contract = this.contractDescriptions.get(toolName);
    if (!contract) {
      this.logger.warn(`No description found for tool: ${toolName}`);
      return `Tool: ${toolName}`;
    }

    if (!this.frameworksConfig.dynamicToolDescriptions) {
      this.logger.debug(
        `Dynamic tool descriptions disabled; using base description for ${toolName}`
      );
      return contract.description;
    }

    if (activeFrameworkType === undefined) {
      return (this.descriptions.get(toolName) ?? contract).description;
    }

    const overlay = this.resolveOverlay(
      toolName,
      frameworkEnabled,
      activeFrameworkType,
      options?.applyFrameworkOverride ?? true
    );
    this.logger.debug(
      `Getting description for ${toolName} (framework enabled: ${frameworkEnabled}, framework: ${activeFrameworkType}, guidance: ${overlay ? 'yes' : 'no'})`
    );
    return overlay
      ? composeToolDescription(contract.description, overlay.tool, overlay.label)
      : contract.description;
  }

  /** The description served for one parameter; same resolution as {@link getDescription}. */
  getParameterDescription(
    toolName: string,
    paramName: string,
    frameworkEnabled?: boolean,
    activeFrameworkType?: string,
    options?: { applyFrameworkOverride?: boolean }
  ): string | undefined {
    const contract = this.contractDescriptions.get(toolName);
    if (!contract) {
      return undefined;
    }
    const contractText = parameterText(contract.parameters?.[paramName]);

    if (!this.frameworksConfig.dynamicToolDescriptions) {
      return contractText;
    }

    if (activeFrameworkType === undefined) {
      return (
        parameterText(this.descriptions.get(toolName)?.parameters?.[paramName]) ?? contractText
      );
    }

    const overlay = this.resolveOverlay(
      toolName,
      frameworkEnabled,
      activeFrameworkType,
      options?.applyFrameworkOverride ?? true
    );
    return overlay
      ? composeParameterDescription(contractText, overlay.tool, paramName, overlay.label)
      : contractText;
  }

  getStats(): {
    totalDescriptions: number;
    loadedFromFile: number;
    usingDefaults: number;
    isInitialized: boolean;
    source: string;
  } {
    const loadedFromFile = this.lastLoadSource === 'defaults' ? 0 : this.descriptions.size || 0;
    const usingDefaults = this.lastLoadSource === 'defaults' ? this.contractDescriptions.size : 0;

    return {
      totalDescriptions: this.descriptions.size,
      loadedFromFile,
      usingDefaults,
      isInitialized: this.isInitialized,
      source: this.lastLoadSource,
    };
  }

  async reload(): Promise<void> {
    await this.synchronize('reload');
  }

  shutdown(): void {
    if (this.frameworksConfigListener) {
      this.configManager.off('frameworksConfigChanged', this.frameworksConfigListener);
    }
    if (this.frameworkStateStore && this.frameworkSwitchedListener) {
      this.frameworkStateStore.off('framework-switched', this.frameworkSwitchedListener);
    }
    if (this.frameworkStateStore && this.frameworkToggledListener) {
      this.frameworkStateStore.off('framework-system-toggled', this.frameworkToggledListener);
    }
    this.removeAllListeners();
  }
}

export function createToolDescriptionLoader(
  logger: Logger,
  configManager: ConfigManager
): ToolDescriptionLoader {
  return new ToolDescriptionLoader(logger, configManager);
}
