// @lifecycle canonical - Re-exports from shared layer (canonical location).
export type {
  CategoryInjectionConfig,
  ChainInjectionConfig,
  ExecutionContextType,
  InjectionCondition,
  InjectionConditionWhen,
  InjectionConfig,
  InjectionDecision,
  InjectionDecisionInput,
  InjectionDecisionSource,
  InjectionDefaults,
  InjectionFrequency,
  InjectionFrequencyMode,
  InjectionRuntimeOverride,
  InjectionSessionState,
  InjectionState,
  InjectionTarget,
  InjectionType,
  InjectionTypeConfig,
  InjectionTypeRuleConfig,
  PromptInjectionConfig,
  PromptInjectionRule,
  ResolvedInjectionConfig,
  StepInjectionConfig,
} from '#shared/types/injection.js';
