export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'server',
        'runtime',
        'pipeline',
        'gates',
        'frameworks',
        'prompts',
        'chains',
        'styles',
        'scripts',
        'hooks',
        'resources',
        'mcp-tools',
        'contracts',
        'parsers',
        'ci',
        'deps',
        'config',
        'logging',
        'metrics',
        'docs',
        'tests',
        'semantic',
        'execution',
      ],
    ],
    'scope-empty': [0, 'never'],
    'header-max-length': [2, 'always', 100],
  },
};
