// Auto-generated by scripts/generate-config-schema.ts from src/shared/types/config-file.ts.
// Do not edit manually — run `npm run generate:config-schema`. `npm run validate:config-schema`
// fails when this file and the generator disagree.
//
// The text `cpm config init` writes as a workspace `config.jsonc`. Every setting it shows, and
// every description, default and permitted-value list beside it, is read out of the same schema
// the loader validates against — so the example file a user edits cannot describe a setting the
// server does not have.

/**
 * A ready-to-edit `config.jsonc`: `$schema` and `version` live, every setting beneath them
 * commented out with its description, its default and its permitted values.
 *
 * Uncommenting one setting's line together with the braces of the sections it sits in yields a
 * document that still parses and still validates — every example line ends with a comma so that
 * holds for a single line as much as for all of them.
 */
export const CONFIG_JSONC_TEMPLATE: string = `// Configuration for the claude-prompts MCP server.
//
// Every setting is listed below, commented out, showing the value it already uses. To change
// one, uncomment its line and the braces of the section around it. Anything left commented
// keeps its default, so a file with nothing uncommented behaves exactly like no file at all.
//
// Comments and trailing commas are both fine here — that is what the .jsonc extension buys.
// Uncomment a single line and the file still parses; there are no commas to fix afterwards.
//
// A plain config.json is still read if you prefer one. It simply cannot carry comments.

{
//   — JSON Schema reference for IDE validation.
  "$schema": "./config.schema.json",

//   — Config file format version. \`5\` is the shape this file describes; an older file declares
//     its own version and is migrated before it reaches this type.
  "version": 5,

//   — Server identity and transport settings.
//   "server": {
//     — Server name reported to MCP clients.
//     — default: "claude-prompts"
//     "name": "claude-prompts",

//     — Port for the Streamable HTTP transport (ignored for stdio).
//     — default: 9090, minimum: 1024, maximum: 65535
//     "port": 9090,
//   },

//   — Prompt loading and registration.
//   "prompts": {
//     — Directory containing prompt definitions (relative to server root).
//     — default: "resources/prompts"
//     "directory": "resources/prompts",

//     — Register prompts as MCP resources for client discovery.
//     — default: true
//     "registerWithMcp": true,
//   },

//   — Identity and client-profile resolution for scope isolation and delegation routing.
//   "identity": {
//     — Identity precedence mode.
//     — default: "permissive"
//     — one of: "permissive", "locked"
//     "mode": "permissive",

//     — Allow request claims to override launch defaults based on transport policy.
//     — default: true
//     "allowPerRequestOverride": true,

//     — Launch-time defaults used when request identity/profile metadata is missing.
//     "launchDefaults": {
//       — Default organization scope.
//       — no default
//       "organizationId": "<organizationId>",

//       — Default workspace scope.
//       — no default
//       "workspaceId": "<workspaceId>",

//       — Authoritative launch-level client family for delegation routing.
//       — no default
//       — one of: "claude-code", "codex", "gemini", "opencode", "cursor", "unknown"
//       "clientFamily": "claude-code",

//       — Authoritative launch-level client identifier.
//       — no default
//       "clientId": "<clientId>",

//       — Authoritative launch-level client version.
//       — no default
//       "clientVersion": "<clientVersion>",

//       — Authoritative launch-level delegation profile.
//       — no default
//       — one of: "task_tool_v1", "spawn_agent_v1", "gemini_subagent_v1", "opencode_agent_v1",
//         "cursor_agent_v1", "neutral_v1"
//       "delegationProfile": "task_tool_v1",
//     },
//   },

//   — Frameworks (CAGEERF, ReACT, etc.) that guide LLM behavior.
//   "frameworks": {
//     — Enable framework system.
//     — default: true
//     "enabled": true,

//     — Adapt MCP tool descriptions based on active framework.
//     — default: true
//     "dynamicToolDescriptions": true,

//     — Framework a scope falls back to when it has no persisted state row. Set per project to
//       pin a repo to one framework (e.g. 'RADIANT' for design work). A runtime framework
//       switch overrides this for that scope and persists.
//     — default: "CAGEERF"
//     "defaultFramework": "CAGEERF",

//     — Injection control for framework content.
//     "injection": {
//       — System prompt injection settings.
//       "systemPrompt": {
//         — Inject framework system-prompt guidance at all.
//         — default: true
//         "enabled": true,

//         — Inject framework guidance every N chain steps. Higher values reduce token usage at
//           the cost of less frequent framework reinforcement.
//         — default: 3, minimum: 1, maximum: 100
//         "frequency": 3,

//         — Where to inject framework guidance: 'steps' (normal execution), 'gates' (gate
//           reviews), or 'both'.
//         — default: "steps"
//         — one of: "steps", "gates", "both"
//         "target": "steps",
//       },

//       — Gate guidance injection settings.
//       "gateGuidance": {
//         — Inject gate criteria every N chain steps. 0 = first step only. Gate review steps
//           always receive guidance regardless of this setting.
//         — default: 0, minimum: 0, maximum: 100
//         "frequency": 0,

//         — Where to inject gate criteria: 'steps' (normal execution), 'gates' (gate reviews),
//           or 'both'.
//         — default: "both"
//         — one of: "steps", "gates", "both"
//         "target": "both",
//       },

//       — Style guidance injection settings.
//       "styleGuidance": {
//         — Include response formatting guidance in prompts.
//         — default: true
//         "enabled": true,

//         — Inject style guidance every N chain steps. 0 = first step only. Set to 1 for every
//           step.
//         — default: 0, minimum: 0, maximum: 100
//         "frequency": 0,

//         — Where to inject style guidance: 'steps' (normal execution), 'gates' (gate reviews),
//           or 'both'.
//         — default: "steps"
//         — one of: "steps", "gates", "both"
//         "target": "steps",
//       },
//     },
//   },

//   — Quality gates for validating LLM outputs.
//   "gates": {
//     — Enable the gate validation system.
//     — default: true
//     "enabled": true,

//     — Apply framework-specific quality gates.
//     — default: true
//     "frameworkGates": true,

//     — Execute a prompt's gateConfiguration.inline_gate_definitions block instead of only
//       displaying it. Off by default this release so an operator can watch the 'Dropped inline
//       gate definition' warnings and see which workspace prompts would newly arm a gate; set
//       true to opt in early. The next release makes true the default.
//     — default: false
//     "executeInlineGateDefinitions": false,

//     — Judge evaluation defaults.
//     "evaluation": {
//       — Default evaluation mode for all gates: 'self' (same-context review) or 'judge'
//         (context-isolated delegation).
//       — default: "self"
//       — one of: "self", "judge"
//       "defaultMode": "self",

//       — Default model hint for judge sub-agents (e.g., 'haiku' for cheap evaluation).
//       — no default
//       "defaultModel": "<defaultModel>",

//       — Default strict mode: use failure-first framing for judge evaluation. Absent, its
//         effective default is not a constant: \`resolveJudgeConfig\` (\`judge-prompt-builder.ts\`)
//         falls back to \`true\` exactly when the evaluation mode is \`'judge'\`, and to \`false\`
//         otherwise.
//       — no default
//       "strict": false,
//     },

//     — Reminder subjects this installation's harness already covers (its own rules or hooks).
//       A reminder gate whose \`subject\` is listed is not rendered; checks are never suppressed.
//     — default: []
//     "harnessCovers": [],

//     — Estimated tokens of reminder guidance rendered per dispatch. Reminders over the budget
//       render as one line each, in priority order; nothing is dropped. Checks are outside the
//       budget.
//     — default: 800, minimum: 0
//     "reminderTokenBudget": 800,
//   },

//   — Ralph Loops: autonomous verification via shell commands.
//   "verification": {
//     — Fix attempts within current context before spawning isolation. Set to 0 for immediate
//       isolation.
//     — default: 3, minimum: 0, maximum: 10
//     "inContextAttempts": 3,

//     — Context isolation settings.
//     "isolation": {
//       — Enable spawning isolated Claude instances after in-context attempts fail.
//       — default: true
//       "enabled": true,

//       — Maximum cost (USD) per isolation spawn.
//       — default: 1, minimum: 0.01, maximum: 10
//       "maxBudget": 1,

//       — Timeout in seconds for each isolation spawn.
//       — default: 300, minimum: 30, maximum: 3600
//       "timeout": 300,

//       — How spawned instance handles permission requests.
//       — default: "delegate"
//       — one of: "delegate", "ask", "deny"
//       "permissionMode": "delegate",
//     },
//   },

//   — Prompt version control.
//   "versioning": {
//     — Track prompt versions.
//     — default: true
//     "enabled": true,

//     — Auto-create versions on prompt changes.
//     — default: true
//     "autoVersion": true,

//     — Maximum versions to retain per prompt.
//     — default: 50, minimum: 1, maximum: 500
//     "maxVersions": 50,
//   },

//   — Deterministic structural validation of LLM output against framework phase definitions.
//   "phaseGuards": {
//     — Enforcement mode: 'enforce' blocks advancement until structural requirements pass,
//       'warn' logs advisory warnings, 'off' disables phase guards.
//     — default: "enforce"
//     — one of: "enforce", "warn", "off"
//     "mode": "enforce",

//     — Maximum retry attempts before phase guard review expires (enforce mode only).
//     — default: 2, minimum: 0, maximum: 10
//     "maxRetries": 2,
//   },

//   — Prompt execution behavior.
//   "execution": {
//     — Enable %judge modifier for framework comparison.
//     — default: true
//     "judge": true,
//   },

//   — Claude Code hook behavior (affects prompt-suggest.py output).
//   "hooks": {
//     — Show detailed multi-line output instead of compact single-line. Useful for debugging or
//       verbose mode. An absent key resolves to \`false\` in \`hooks/lib/config_loader.py\`.
//     — default: true
//     "expandedOutput": true,
//   },

//   — OpenTelemetry observability: tracing, metrics, and attribute policy.
//   "telemetry": {
//     — Master switch for the telemetry subsystem. When false, no OTel SDK is initialized.
//     — default: false
//     "enabled": false,

//     — Export mode: 'off' (disabled), 'traces' (spans/events only), 'full' (spans + OTel
//       metrics).
//     — default: "off"
//     — one of: "off", "traces", "full"
//     "mode": "off",

//     — OTLP HTTP exporter endpoint URL.
//     — default: "http://localhost:4318"
//     "exporterEndpoint": "http://localhost:4318",

//     — Head sampling rate for traces (0.0-1.0). 1.0 = sample everything, 0.0 = sample nothing.
//     — default: 1, minimum: 0, maximum: 1
//     "samplingRate": 1,

//     — Controls which attributes are included in trace spans and events for data safety.
//     "attributePolicy": {
//       — Include safe business-context attributes (cpm.prompt.id, cpm.execution.mode, etc.).
//       — default: true
//       "businessContext": true,

//       — Include raw command text in traces. WARNING: may contain sensitive data.
//       — default: false
//       "rawCommands": false,

//       — Include raw user responses in traces. WARNING: may contain sensitive data.
//       — default: false
//       "rawResponses": false,

//       — Custom attribute names to explicitly include in traces.
//       — no default
//       "allowlist": [],
//     },
//   },

//   — Server logging configuration.
//   "logging": {
//     — Minimum log level.
//     — default: "info"
//     — one of: "error", "warn", "info", "debug"
//     "level": "info",

//     — Log file directory.
//     — default: "./logs"
//     "directory": "./logs",
//   },

//   — MCP resources configuration.
//   "resources": {
//     — Master switch: register resources with MCP protocol (default: false for token
//       efficiency).
//     — default: false
//     "registerWithMcp": false,

//     — Prompt resources (resource://prompt/...).
//     "prompts": {
//       — Enable this resource family.
//       — default: true
//       "enabled": true,
//     },

//     — Gate resources (resource://gate/...).
//     "gates": {
//       — Enable this resource family.
//       — default: true
//       "enabled": true,
//     },

//     — Framework resources (resource://framework/...).
//     "frameworks": {
//       — Enable this resource family.
//       — default: true
//       "enabled": true,
//     },

//     — Observability resources (sessions and metrics).
//     "observability": {
//       — Enable observability resources.
//       — default: true
//       "enabled": true,

//       — Enable session resources (resource://session/...).
//       — default: true
//       "sessions": true,

//       — Enable metrics resources (resource://metrics/...).
//       — default: true
//       "metrics": true,
//     },

//     — Logs resource for debugging and observability.
//     "logs": {
//       — Enable logs resource (resource://logs/).
//       — default: true
//       "enabled": true,

//       — Maximum log entries to retain in memory.
//       — default: 500, minimum: 50, maximum: 5000
//       "maxEntries": 500,

//       — Minimum level to buffer (entries below this level are not stored).
//       — default: "info"
//       — one of: "error", "warn", "info", "debug"
//       "defaultLevel": "info",
//     },
//   },

//   — Chain session lifecycle management.
//   "chainSessions": {
//     — Idle session timeout in minutes (default: 24 hours).
//     — default: 1440, minimum: 1, maximum: 10080
//     "timeoutMinutes": 1440,

//     — Gate review timeout in minutes.
//     — default: 30, minimum: 1, maximum: 10080
//     "reviewTimeoutMinutes": 30,

//     — Background cleanup frequency in minutes.
//     — default: 5, minimum: 1, maximum: 10080
//     "cleanupIntervalMinutes": 5,
//   },
}
`;
