// Auto-generated by scripts/generate-config-schema.ts from src/shared/types/config-file.ts.
// Do not edit manually — run `npm run generate:config-schema`. `npm run validate:config-schema`
// fails when this file and the generator disagree.
//
// This is the ONE table `config-input-validator.ts` validates against, so a key an operator may
// set, the constraint it is checked by, and the schema the loader validates the whole document
// against all come from one declaration: `ConfigFile` (src/shared/types/config-file.ts).

/** The subset of JSON Schema a settable config leaf may carry. */
export interface ConfigLeafRule {
  readonly type: 'string' | 'integer' | 'number' | 'boolean' | 'array';
  /** Permitted values for a `string` leaf, in schema order. */
  readonly enum?: readonly string[];
  readonly minimum?: number;
  readonly maximum?: number;
  /** Element contract for an `array` leaf. */
  readonly items?: { readonly type: string; readonly pattern?: string };
}

/**
 * Every dotted key an operator may set, sorted. Derived from the leaves of
 * `config.schema.json` minus the document-level members (`$schema`, `version`), which decide
 * how the file is READ rather than what it configures.
 */
export const CONFIG_VALID_KEYS = [
  'chainSessions.cleanupIntervalMinutes',
  'chainSessions.reviewTimeoutMinutes',
  'chainSessions.timeoutMinutes',
  'execution.judge',
  'frameworks.defaultFramework',
  'frameworks.dynamicToolDescriptions',
  'frameworks.enabled',
  'frameworks.injection.gateGuidance.frequency',
  'frameworks.injection.gateGuidance.target',
  'frameworks.injection.styleGuidance.enabled',
  'frameworks.injection.styleGuidance.frequency',
  'frameworks.injection.styleGuidance.target',
  'frameworks.injection.systemPrompt.enabled',
  'frameworks.injection.systemPrompt.frequency',
  'frameworks.injection.systemPrompt.target',
  'gates.enabled',
  'gates.evaluation.defaultMode',
  'gates.evaluation.defaultModel',
  'gates.evaluation.strict',
  'gates.executeInlineGateDefinitions',
  'gates.frameworkGates',
  'gates.harnessCovers',
  'gates.reminderTokenBudget',
  'hooks.expandedOutput',
  'identity.allowPerRequestOverride',
  'identity.launchDefaults.clientFamily',
  'identity.launchDefaults.clientId',
  'identity.launchDefaults.clientVersion',
  'identity.launchDefaults.delegationProfile',
  'identity.launchDefaults.organizationId',
  'identity.launchDefaults.workspaceId',
  'identity.mode',
  'logging.directory',
  'logging.level',
  'phaseGuards.maxRetries',
  'phaseGuards.mode',
  'prompts.directory',
  'prompts.registerWithMcp',
  'resources.frameworks.enabled',
  'resources.gates.enabled',
  'resources.logs.defaultLevel',
  'resources.logs.enabled',
  'resources.logs.maxEntries',
  'resources.observability.enabled',
  'resources.observability.metrics',
  'resources.observability.sessions',
  'resources.prompts.enabled',
  'resources.registerWithMcp',
  'server.name',
  'server.port',
  'telemetry.attributePolicy.allowlist',
  'telemetry.attributePolicy.businessContext',
  'telemetry.attributePolicy.rawCommands',
  'telemetry.attributePolicy.rawResponses',
  'telemetry.enabled',
  'telemetry.exporterEndpoint',
  'telemetry.mode',
  'telemetry.samplingRate',
  'verification.inContextAttempts',
  'verification.isolation.enabled',
  'verification.isolation.maxBudget',
  'verification.isolation.permissionMode',
  'verification.isolation.timeout',
  'versioning.autoVersion',
  'versioning.enabled',
  'versioning.maxVersions',
] as const;

export type ConfigKey = (typeof CONFIG_VALID_KEYS)[number];

/**
 * The constraint each key carries. Typed as a total `Record<ConfigKey, …>`, so the compiler —
 * not a convention — is what keeps this table and `CONFIG_VALID_KEYS` naming the same set.
 */
export const CONFIG_KEY_TABLE: Readonly<Record<ConfigKey, ConfigLeafRule>> = {
  'chainSessions.cleanupIntervalMinutes': {
    type: 'integer',
    minimum: 1,
    maximum: 10080,
  },
  'chainSessions.reviewTimeoutMinutes': {
    type: 'integer',
    minimum: 1,
    maximum: 10080,
  },
  'chainSessions.timeoutMinutes': {
    type: 'integer',
    minimum: 1,
    maximum: 10080,
  },
  'execution.judge': {
    type: 'boolean',
  },
  'frameworks.defaultFramework': {
    type: 'string',
  },
  'frameworks.dynamicToolDescriptions': {
    type: 'boolean',
  },
  'frameworks.enabled': {
    type: 'boolean',
  },
  'frameworks.injection.gateGuidance.frequency': {
    type: 'integer',
    minimum: 0,
    maximum: 100,
  },
  'frameworks.injection.gateGuidance.target': {
    type: 'string',
    enum: ['steps', 'gates', 'both'],
  },
  'frameworks.injection.styleGuidance.enabled': {
    type: 'boolean',
  },
  'frameworks.injection.styleGuidance.frequency': {
    type: 'integer',
    minimum: 0,
    maximum: 100,
  },
  'frameworks.injection.styleGuidance.target': {
    type: 'string',
    enum: ['steps', 'gates', 'both'],
  },
  'frameworks.injection.systemPrompt.enabled': {
    type: 'boolean',
  },
  'frameworks.injection.systemPrompt.frequency': {
    type: 'integer',
    minimum: 1,
    maximum: 100,
  },
  'frameworks.injection.systemPrompt.target': {
    type: 'string',
    enum: ['steps', 'gates', 'both'],
  },
  'gates.enabled': {
    type: 'boolean',
  },
  'gates.evaluation.defaultMode': {
    type: 'string',
    enum: ['self', 'judge'],
  },
  'gates.evaluation.defaultModel': {
    type: 'string',
  },
  'gates.evaluation.strict': {
    type: 'boolean',
  },
  'gates.executeInlineGateDefinitions': {
    type: 'boolean',
  },
  'gates.frameworkGates': {
    type: 'boolean',
  },
  'gates.harnessCovers': {
    type: 'array',
    items: { type: 'string', pattern: '^[a-z0-9]+(?:-[a-z0-9]+)*$' },
  },
  'gates.reminderTokenBudget': {
    type: 'integer',
    minimum: 0,
  },
  'hooks.expandedOutput': {
    type: 'boolean',
  },
  'identity.allowPerRequestOverride': {
    type: 'boolean',
  },
  'identity.launchDefaults.clientFamily': {
    type: 'string',
    enum: ['claude-code', 'codex', 'gemini', 'opencode', 'cursor', 'unknown'],
  },
  'identity.launchDefaults.clientId': {
    type: 'string',
  },
  'identity.launchDefaults.clientVersion': {
    type: 'string',
  },
  'identity.launchDefaults.delegationProfile': {
    type: 'string',
    enum: [
      'task_tool_v1',
      'spawn_agent_v1',
      'gemini_subagent_v1',
      'opencode_agent_v1',
      'cursor_agent_v1',
      'neutral_v1',
    ],
  },
  'identity.launchDefaults.organizationId': {
    type: 'string',
  },
  'identity.launchDefaults.workspaceId': {
    type: 'string',
  },
  'identity.mode': {
    type: 'string',
    enum: ['permissive', 'locked'],
  },
  'logging.directory': {
    type: 'string',
  },
  'logging.level': {
    type: 'string',
    enum: ['error', 'warn', 'info', 'debug'],
  },
  'phaseGuards.maxRetries': {
    type: 'integer',
    minimum: 0,
    maximum: 10,
  },
  'phaseGuards.mode': {
    type: 'string',
    enum: ['enforce', 'warn', 'off'],
  },
  'prompts.directory': {
    type: 'string',
  },
  'prompts.registerWithMcp': {
    type: 'boolean',
  },
  'resources.frameworks.enabled': {
    type: 'boolean',
  },
  'resources.gates.enabled': {
    type: 'boolean',
  },
  'resources.logs.defaultLevel': {
    type: 'string',
    enum: ['error', 'warn', 'info', 'debug'],
  },
  'resources.logs.enabled': {
    type: 'boolean',
  },
  'resources.logs.maxEntries': {
    type: 'integer',
    minimum: 50,
    maximum: 5000,
  },
  'resources.observability.enabled': {
    type: 'boolean',
  },
  'resources.observability.metrics': {
    type: 'boolean',
  },
  'resources.observability.sessions': {
    type: 'boolean',
  },
  'resources.prompts.enabled': {
    type: 'boolean',
  },
  'resources.registerWithMcp': {
    type: 'boolean',
  },
  'server.name': {
    type: 'string',
  },
  'server.port': {
    type: 'integer',
    minimum: 1024,
    maximum: 65535,
  },
  'telemetry.attributePolicy.allowlist': {
    type: 'array',
    items: { type: 'string' },
  },
  'telemetry.attributePolicy.businessContext': {
    type: 'boolean',
  },
  'telemetry.attributePolicy.rawCommands': {
    type: 'boolean',
  },
  'telemetry.attributePolicy.rawResponses': {
    type: 'boolean',
  },
  'telemetry.enabled': {
    type: 'boolean',
  },
  'telemetry.exporterEndpoint': {
    type: 'string',
  },
  'telemetry.mode': {
    type: 'string',
    enum: ['off', 'traces', 'full'],
  },
  'telemetry.samplingRate': {
    type: 'number',
    minimum: 0,
    maximum: 1,
  },
  'verification.inContextAttempts': {
    type: 'integer',
    minimum: 0,
    maximum: 10,
  },
  'verification.isolation.enabled': {
    type: 'boolean',
  },
  'verification.isolation.maxBudget': {
    type: 'number',
    minimum: 0.01,
    maximum: 10,
  },
  'verification.isolation.permissionMode': {
    type: 'string',
    enum: ['delegate', 'ask', 'deny'],
  },
  'verification.isolation.timeout': {
    type: 'integer',
    minimum: 30,
    maximum: 3600,
  },
  'versioning.autoVersion': {
    type: 'boolean',
  },
  'versioning.enabled': {
    type: 'boolean',
  },
  'versioning.maxVersions': {
    type: 'integer',
    minimum: 1,
    maximum: 500,
  },
};
