// @lifecycle canonical - Execution-level shared type definitions.
/**
 * Execution System Type Definitions
 *
 * Contains all types related to prompt execution, strategies, contexts, and results.
 * This includes execution strategies, converted prompts, contexts, and chain execution.
 */

import type { GateDefinition, PromptArgument } from '../prompts/types.js';
import type { LoadedScriptTool } from '../scripts/types.js';
import type {
  CustomCheck,
  GateScope,
  GateSpecification,
  TemporaryGateInput,
} from '../types/execution.js';

// Re-export gate-related types for convenience
export type { CustomCheck, GateScope, GateSpecification, TemporaryGateInput };

/**
 * Execution modifiers control pipeline behavior.
 * - clean: Skip all injection (system-prompt, gate-guidance, style-guidance)
 * - judge: Trigger judge selection phase for resource menu (%judge in command)
 * - lean: Skip system-prompt and style-guidance, keep gate-guidance only
 * - framework: Force framework methodology injection
 */
export type ExecutionModifier = 'clean' | 'judge' | 'lean' | 'framework';

export interface ExecutionModifiers {
  clean?: boolean;
  /** Triggers judge selection phase. Use %judge in command. */
  judge?: boolean;
  lean?: boolean;
  framework?: boolean;
}

/**
 * Execution strategy type enumeration - THREE-TIER MODEL
 * Used by ExecutionEngine's strategy pattern for different execution modes
 *
 * - single: Unified single prompt execution with optional modifiers for framework/gate behavior
 * - chain: Sequential execution using prompts (includes former workflow capabilities)
 */
export type ExecutionStrategyType = 'single' | 'chain';

/**
 * Execution plan generated by the ExecutionPlanner
 * Contains strategy, gate configuration, and execution requirements
 */
export interface ExecutionPlan {
  strategy: ExecutionStrategyType;
  gates: string[];
  requiresFramework: boolean;
  requiresSession: boolean;
  category?: string;
  modifiers?: ExecutionModifiers;
  /** Semantic analysis result from planning phase (for resource-driven guidance) */
  semanticAnalysis?: import('../semantic/types.js').ContentAnalysisResult;
}

/**
 * Execution types for semantic analysis
 */
export type ExecutionType = 'single' | 'chain' | 'auto';

/**
 * Chain step definition
 *
 * Defines a single step in a chain workflow with support for:
 * - inputMapping: Map previous step results to semantic variable names
 * - outputMapping: Name this step's output for downstream reference
 * - retries: Per-step retry count for resilient chains
 */
export interface ChainStep {
  /** ID of the prompt to execute in this step */
  promptId: string;
  /** Name/identifier of this step */
  stepName: string;
  /** Map step results to semantic names (e.g., { "research": "step1_result" }) */
  inputMapping?: Record<string, string>;
  /** Name this step's output for downstream steps */
  outputMapping?: Record<string, string>;
  /** Number of retry attempts on failure (default: 0) */
  retries?: number;
}

/**
 * Comprehensive converted prompt for execution context
 * Consolidates all previous ConvertedPrompt definitions
 */
export interface ConvertedPrompt {
  id: string;
  name: string;
  description: string;
  category: string;
  systemMessage?: string;
  userMessageTemplate: string;
  arguments: PromptArgument[];
  // Chain-related properties (isChain removed - now derived from chainSteps presence)
  chainSteps?: ChainStep[];
  // Gate validation properties
  gates?: GateDefinition[];
  /** Whether to register this prompt with MCP. Resolved from prompt/category/global defaults. */
  registerWithMcp?: boolean;
  // Template-level gate configuration
  gateConfiguration?: {
    include?: string[];
    exclude?: string[];
    framework_gates?: boolean;
  };
  // Enhanced gate configuration with temporary gates
  enhancedGateConfiguration?: EnhancedGateConfiguration;
  executionModifiers?: ExecutionModifiers; // Optional default modifiers applied when executing this prompt
  requiresExecution?: boolean; // Whether this prompt should be executed rather than returned
  // Script tools
  /** Loaded script tools for this prompt (populated by loader when tools declared in prompt.yaml) */
  scriptTools?: LoadedScriptTool[];
  /** Raw tool IDs from prompt definition (before loading) */
  tools?: string[];
  /** Directory path for prompt-local script resolution (populated during conversion) */
  promptDir?: string;
}

/**
 * Base execution context for all strategies
 * Provides common execution metadata across all strategy types
 */
export interface BaseExecutionContext {
  /** Unique execution identifier */
  id: string;
  /** Strategy type being used */
  type: ExecutionStrategyType;
  /** Execution start timestamp */
  startTime: number;
  /** Input parameters for execution */
  inputs: Record<string, string | number | boolean | null>;
  /** Strategy-specific and user options */
  options: Record<string, string | number | boolean | null | unknown[]>;
}

/**
 * Chain step execution result
 */
export interface ChainStepResult {
  result: string;
  metadata: {
    startTime: number;
    endTime: number;
    duration: number;
    status: 'completed' | 'failed' | 'skipped';
    error?: string;
  };
}

/**
 * Chain execution result structure
 */
export interface ChainExecutionResult {
  results: Record<string, string>;
  messages: {
    role: 'user' | 'assistant';
    content: { type: 'text'; text: string };
  }[];
}

/**
 * Unified execution result interface
 * Standardizes results across all execution strategies
 */
export interface UnifiedExecutionResult {
  /** Unique execution identifier */
  executionId: string;
  /** Strategy type that was used */
  type: ExecutionStrategyType;
  /** Final execution status */
  status: 'completed' | 'failed' | 'timeout' | 'cancelled';
  /** Execution start timestamp */
  startTime: number;
  /** Execution end timestamp */
  endTime: number;
  /** Strategy-specific result content */
  result: string | ChainExecutionResult;
  /** Error information if execution failed */
  error?: {
    message: string;
    code?: string;
    context?: Record<string, unknown>;
  };
}

/**
 * Base execution strategy interface
 * Defines the contract that all execution strategies must implement
 */
export interface ExecutionStrategy {
  /** Strategy type identifier */
  readonly type: ExecutionStrategyType;

  /**
   * Execute using this strategy
   * @param context Base execution context
   * @param promptId ID of prompt to execute
   * @param args Execution arguments
   */
  execute(
    context: BaseExecutionContext,
    promptId: string,
    args: Record<string, string | number | boolean | null>
  ): Promise<UnifiedExecutionResult>;

  /**
   * Validate if this strategy can handle the given prompt
   * @param prompt The prompt to validate
   */
  canHandle(prompt: ConvertedPrompt): boolean;

  /**
   * Get strategy-specific default options
   */
  getOptions(): Record<string, string | number | boolean | null | unknown[]>;
}

/**
 * Execution engine statistics
 * Comprehensive performance and usage metrics
 */
export interface ExecutionStats {
  /** Total number of executions */
  totalExecutions: number;
  /** Number of prompt strategy executions */
  promptExecutions: number;
  /** Number of chain strategy executions */
  chainExecutions: number;
  /** Number of failed executions */
  failedExecutions: number;
  /** Average execution time in milliseconds */
  averageExecutionTime: number;
  /** Currently active executions */
  activeExecutions: number;
  /** Conversation manager statistics */
  conversationStats: any;
}

/**
 * Performance metrics for ExecutionEngine monitoring
 * Provides detailed performance and health metrics
 */
export interface PerformanceMetrics {
  /** Strategy cache hit rate (0.0 to 1.0) */
  cacheHitRate: number;
  /** Memory usage information */
  memoryUsage: {
    /** Size of strategy selection cache */
    strategyCacheSize: number;
    /** Number of stored execution times */
    executionTimesSize: number;
    /** Number of currently active executions */
    activeExecutionsSize: number;
  };
  /** Execution health metrics */
  executionHealth: {
    /** Success rate (0.0 to 1.0) */
    successRate: number;
    /** Average execution time in milliseconds */
    averageTime: number;
    /** Number of recent executions tracked */
    recentExecutions: number;
  };
}

/**
 * Chain execution state
 */
export interface ChainExecutionState {
  chainId: string;
  currentStepIndex: number;
  totalSteps: number;
  stepResults: Record<string, string>;
  startTime: number;
}

/**
 * Template processing context
 */
export interface TemplateContext {
  specialContext?: Record<string, string>;
}

/**
 * Validation error detail structure
 */
export interface ValidationError {
  field: string;
  message: string;
  code: string;
  suggestion?: string;
  example?: string;
}

/**
 * Validation warning structure
 */
export interface ValidationWarning {
  field: string;
  message: string;
  suggestion?: string;
}

/**
 * Unified validation result structure
 * Supports both simple validation and comprehensive gate validation
 */
export interface ValidationResult {
  /** Whether validation passed (supports both 'valid' and 'passed' patterns) */
  valid: boolean;
  /** Alternative field name for gate validation compatibility */
  passed?: boolean;
  /** Detailed validation errors */
  errors?: ValidationError[];
  /** Validation warnings */
  warnings?: ValidationWarning[];
  /** Sanitized arguments for simple validation */
  sanitizedArgs?: Record<string, string | number | boolean | null>;

  // Extended fields for gate validation (optional)
  /** Gate that was validated (for gate validation) */
  gateId?: string;
  /** Individual check results (for comprehensive validation) */
  checks?: ValidationCheck[];
  /** Hints for improvement on failure (for gate validation) */
  retryHints?: string[];
  /** Validation metadata (for comprehensive validation) */
  metadata?: {
    validationTime: number;
    checksPerformed: number;
    llmValidationUsed: boolean;
  };

  // Argument-specific validation (optional)
  /** Argument name (for argument validation) */
  argumentName?: string;
  /** Original value before processing */
  originalValue?: unknown;
  /** Processed value after validation */
  processedValue?: string | number | boolean | null;
  /** Applied validation rules */
  appliedRules?: string[];
}

/**
 * Individual validation check result (used in comprehensive validation)
 */
export interface ValidationCheck {
  /** Type of check performed */
  type: string;
  /** Did this check pass */
  passed: boolean;
  /** Score if applicable (0.0-1.0) */
  score?: number;
  /** Details about the check */
  message: string;
  /** Additional context */
  details?: Record<string, any>;
}

/**
 * Enhanced gate configuration supporting inline gate definitions
 * Extends basic gate configuration with inline gate support
 */
export interface EnhancedGateConfiguration {
  /** Gates to explicitly include */
  include?: string[];
  /** Gates to explicitly exclude */
  exclude?: string[];
  /** Whether to include framework-based gates (default: true) */
  framework_gates?: boolean;
  /** Inline gate definitions for this execution */
  inline_gate_definitions?: TemporaryGateDefinition[];
}

/**
 * Temporary gate definition for enhanced configuration
 */
export interface TemporaryGateDefinition {
  /** Unique identifier (will be auto-generated if not provided) */
  id?: string;
  /** Human-readable name */
  name: string;
  /** Gate type: 'validation' runs checks, 'guidance' only provides instructional text */
  type: 'validation' | 'guidance';
  /** Scope of the temporary gate */
  scope: 'execution' | 'session' | 'chain' | 'step';
  /** Description of what this gate checks/guides */
  description: string;
  /** Guidance text injected into prompts */
  guidance: string;
  /** Pass/fail criteria for validation gates */
  pass_criteria?: ValidationCheck[];
  /** Expiration timestamp (optional) */
  expires_at?: number;
  /** Source of gate creation */
  source?: 'manual' | 'automatic' | 'analysis';
  /** Additional context for gate creation */
  context?: Record<string, any>;
}

/**
 * Captures execution context supplied to gate review prompts so reviewers
 * can reference original arguments and prior results without relying on history.
 */
export interface GateReviewExecutionContext {
  originalArgs: Record<string, unknown>;
  previousResults: Record<number, string>;
  currentStep?: number;
  totalSteps?: number;
  chainId?: string;
  sessionId?: string;
}

/**
 * Structured review prompt emitted by gate validation when a manual review is required.
 */
export interface GateReviewPrompt {
  gateId?: string;
  gateName?: string;
  criteriaSummary: string;
  promptTemplate?: string;
  explicitInstructions?: string[];
  retryHints?: string[];
  previousResponse?: string;
  executionContext?: GateReviewExecutionContext;
  metadata?: Record<string, unknown>;
}
